Use correct to-function dependency
Since the branch was merged (and probably deleted) upstream, I get the following error when installing:
Error: can't find remote for "component/to-function"